version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    links:
      - "db:db"

  db:
    image: postgres
    volumes:
      - digitalhub_development_db:/var/lib/postgresql/data
    env_file: 
      - ./.env


volumes:
  - digitalhub_development_db
